-- ============================================================
-- База данных для ВКР:
-- "Интеллектуальная система подготовки авиадиспетчеров
--  с использованием нейросетевых моделей"
--
-- PostgreSQL. Скрипт создает структуру БД без заполнения данными.
-- ============================================================

-- ------------------------------------------------------------
-- 1. Создание базы данных
-- ------------------------------------------------------------
-- Команду CREATE DATABASE нужно выполнять, подключившись к служебной БД,
-- например postgres. Если база уже создана, этот блок можно пропустить.

-- CREATE DATABASE vkr_atc_training
--     WITH
--     ENCODING = 'UTF8'
--     TEMPLATE = template0;

-- После создания базы подключитесь к ней:
-- \connect vkr_atc_training

-- ------------------------------------------------------------
-- 2. Схема приложения
-- ------------------------------------------------------------

CREATE SCHEMA IF NOT EXISTS app;
SET search_path TO app, public;

-- ------------------------------------------------------------
-- 3. Перечислимые типы
-- ------------------------------------------------------------

DO $$
BEGIN
    CREATE TYPE app.phrase_role AS ENUM ('pilot', 'controller', 'both');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$
BEGIN
    CREATE TYPE app.difficulty_level AS ENUM ('basic', 'intermediate', 'advanced');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$
BEGIN
    CREATE TYPE app.noise_type AS ENUM ('none', 'file', 'generated');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$
BEGIN
    CREATE TYPE app.generation_status AS ENUM ('processing', 'success', 'failed');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$
BEGIN
    CREATE TYPE app.test_type AS ENUM ('choice', 'manual_input');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- ------------------------------------------------------------
-- 4. Служебная функция обновления updated_at
-- ------------------------------------------------------------

CREATE OR REPLACE FUNCTION app.set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- ------------------------------------------------------------
-- 5. Справочник категорий фраз
-- ------------------------------------------------------------

CREATE TABLE IF NOT EXISTS app.phrase_categories (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code        VARCHAR(64)  NOT NULL UNIQUE,
    name_ru     VARCHAR(255) NOT NULL,
    name_en     VARCHAR(255) NOT NULL,
    description TEXT,
    is_active   BOOLEAN NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT chk_phrase_categories_code_not_blank
        CHECK (btrim(code) <> ''),
    CONSTRAINT chk_phrase_categories_name_ru_not_blank
        CHECK (btrim(name_ru) <> ''),
    CONSTRAINT chk_phrase_categories_name_en_not_blank
        CHECK (btrim(name_en) <> '')
);

DROP TRIGGER IF EXISTS trg_phrase_categories_set_updated_at ON app.phrase_categories;
CREATE TRIGGER trg_phrase_categories_set_updated_at
BEFORE UPDATE ON app.phrase_categories
FOR EACH ROW
EXECUTE FUNCTION app.set_updated_at();

-- ------------------------------------------------------------
-- 6. Учебные авиационные фразы
-- ------------------------------------------------------------

CREATE TABLE IF NOT EXISTS app.aviation_phrases (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id      BIGINT NOT NULL,
    phrase_text      TEXT NOT NULL,
    phrase_template  TEXT,
    example_text     TEXT,
    role             app.phrase_role NOT NULL DEFAULT 'both',
    difficulty_level app.difficulty_level NOT NULL DEFAULT 'basic',
    is_active        BOOLEAN NOT NULL DEFAULT TRUE,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at       TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT fk_aviation_phrases_category
        FOREIGN KEY (category_id)
        REFERENCES app.phrase_categories (id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT chk_aviation_phrases_phrase_text_not_blank
        CHECK (btrim(phrase_text) <> ''),

    CONSTRAINT uq_aviation_phrases_category_phrase
        UNIQUE (category_id, phrase_text)
);

DROP TRIGGER IF EXISTS trg_aviation_phrases_set_updated_at ON app.aviation_phrases;
CREATE TRIGGER trg_aviation_phrases_set_updated_at
BEFORE UPDATE ON app.aviation_phrases
FOR EACH ROW
EXECUTE FUNCTION app.set_updated_at();

-- ------------------------------------------------------------
-- 7. Справочник акцентов
-- ------------------------------------------------------------

CREATE TABLE IF NOT EXISTS app.accents (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code              VARCHAR(64)  NOT NULL UNIQUE,
    name_ru           VARCHAR(255) NOT NULL,
    name_en           VARCHAR(255) NOT NULL,
    tts_language_code VARCHAR(64)  NOT NULL,
    tts_speaker_code  VARCHAR(64),
    is_active         BOOLEAN NOT NULL DEFAULT TRUE,
    created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at        TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT chk_accents_code_not_blank
        CHECK (btrim(code) <> ''),
    CONSTRAINT chk_accents_name_ru_not_blank
        CHECK (btrim(name_ru) <> ''),
    CONSTRAINT chk_accents_name_en_not_blank
        CHECK (btrim(name_en) <> ''),
    CONSTRAINT chk_accents_tts_language_code_not_blank
        CHECK (btrim(tts_language_code) <> '')
);

DROP TRIGGER IF EXISTS trg_accents_set_updated_at ON app.accents;
CREATE TRIGGER trg_accents_set_updated_at
BEFORE UPDATE ON app.accents
FOR EACH ROW
EXECUTE FUNCTION app.set_updated_at();

-- ------------------------------------------------------------
-- 8. Справочник акустических условий и шумов
-- ------------------------------------------------------------

CREATE TABLE IF NOT EXISTS app.noise_profiles (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code           VARCHAR(64)  NOT NULL UNIQUE,
    name_ru        VARCHAR(255) NOT NULL,
    name_en        VARCHAR(255) NOT NULL,
    noise_type     app.noise_type NOT NULL DEFAULT 'none',
    file_path      TEXT,
    default_snr_db NUMERIC(6, 2),
    is_active      BOOLEAN NOT NULL DEFAULT TRUE,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at     TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT chk_noise_profiles_code_not_blank
        CHECK (btrim(code) <> ''),
    CONSTRAINT chk_noise_profiles_name_ru_not_blank
        CHECK (btrim(name_ru) <> ''),
    CONSTRAINT chk_noise_profiles_name_en_not_blank
        CHECK (btrim(name_en) <> ''),
    CONSTRAINT chk_noise_profiles_file_path_for_file_noise
        CHECK (noise_type <> 'file' OR file_path IS NOT NULL),
    CONSTRAINT chk_noise_profiles_default_snr_positive
        CHECK (default_snr_db IS NULL OR default_snr_db > 0)
);

DROP TRIGGER IF EXISTS trg_noise_profiles_set_updated_at ON app.noise_profiles;
CREATE TRIGGER trg_noise_profiles_set_updated_at
BEFORE UPDATE ON app.noise_profiles
FOR EACH ROW
EXECUTE FUNCTION app.set_updated_at();

-- ------------------------------------------------------------
-- 9. Варианты ответов для тестирования с выбором ответа
-- ------------------------------------------------------------

CREATE TABLE IF NOT EXISTS app.answer_options (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    phrase_id   BIGINT NOT NULL,
    option_text TEXT NOT NULL,
    is_correct  BOOLEAN NOT NULL DEFAULT FALSE,
    is_active   BOOLEAN NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT fk_answer_options_phrase
        FOREIGN KEY (phrase_id)
        REFERENCES app.aviation_phrases (id)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    CONSTRAINT chk_answer_options_option_text_not_blank
        CHECK (btrim(option_text) <> ''),

    CONSTRAINT uq_answer_options_phrase_text
        UNIQUE (phrase_id, option_text)
);

-- Для одной фразы может быть только один корректный вариант ответа.
CREATE UNIQUE INDEX IF NOT EXISTS uq_answer_options_one_correct_per_phrase
    ON app.answer_options (phrase_id)
    WHERE is_correct;

DROP TRIGGER IF EXISTS trg_answer_options_set_updated_at ON app.answer_options;
CREATE TRIGGER trg_answer_options_set_updated_at
BEFORE UPDATE ON app.answer_options
FOR EACH ROW
EXECUTE FUNCTION app.set_updated_at();

-- ------------------------------------------------------------
-- 10. История генерации аудиофайлов
-- ------------------------------------------------------------

CREATE TABLE IF NOT EXISTS app.audio_generations (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    phrase_id        BIGINT NOT NULL,
    accent_id        BIGINT NOT NULL,
    noise_profile_id BIGINT NOT NULL,
    generated_text   TEXT NOT NULL,
    tts_model_name   VARCHAR(128) NOT NULL DEFAULT 'MeloTTS',
    audio_file_path  TEXT,
    duration_ms      INTEGER,
    snr_db           NUMERIC(6, 2),
    status           app.generation_status NOT NULL DEFAULT 'processing',
    error_message    TEXT,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT fk_audio_generations_phrase
        FOREIGN KEY (phrase_id)
        REFERENCES app.aviation_phrases (id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT fk_audio_generations_accent
        FOREIGN KEY (accent_id)
        REFERENCES app.accents (id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT fk_audio_generations_noise_profile
        FOREIGN KEY (noise_profile_id)
        REFERENCES app.noise_profiles (id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT chk_audio_generations_generated_text_not_blank
        CHECK (btrim(generated_text) <> ''),
    CONSTRAINT chk_audio_generations_tts_model_name_not_blank
        CHECK (btrim(tts_model_name) <> ''),
    CONSTRAINT chk_audio_generations_duration_non_negative
        CHECK (duration_ms IS NULL OR duration_ms >= 0),
    CONSTRAINT chk_audio_generations_snr_positive
        CHECK (snr_db IS NULL OR snr_db > 0),
    CONSTRAINT chk_audio_generations_success_has_file
        CHECK (status <> 'success' OR audio_file_path IS NOT NULL),
    CONSTRAINT chk_audio_generations_failed_has_error
        CHECK (status <> 'failed' OR error_message IS NOT NULL)
);

-- ------------------------------------------------------------
-- 11. Тестовые сессии
-- ------------------------------------------------------------

CREATE TABLE IF NOT EXISTS app.test_sessions (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    test_type             app.test_type NOT NULL,
    questions_count       INTEGER NOT NULL DEFAULT 10,
    correct_answers_count INTEGER NOT NULL DEFAULT 0,
    score_percent         NUMERIC(5, 2),
    report_file_path      TEXT,
    started_at            TIMESTAMPTZ NOT NULL DEFAULT now(),
    finished_at           TIMESTAMPTZ,

    CONSTRAINT chk_test_sessions_questions_count_positive
        CHECK (questions_count > 0),
    CONSTRAINT chk_test_sessions_correct_answers_range
        CHECK (correct_answers_count >= 0 AND correct_answers_count <= questions_count),
    CONSTRAINT chk_test_sessions_score_percent_range
        CHECK (score_percent IS NULL OR (score_percent >= 0 AND score_percent <= 100)),
    CONSTRAINT chk_test_sessions_finished_after_started
        CHECK (finished_at IS NULL OR finished_at >= started_at)
);

-- ------------------------------------------------------------
-- 12. Нормализованное хранение выбранных параметров теста
-- ------------------------------------------------------------
-- В info (3).md выбранные категории, акценты и шумы описаны как списки
-- selected_category_ids, selected_accent_ids, selected_noise_profile_ids.
-- Для соблюдения нормальной формы они вынесены в отдельные таблицы связей.

CREATE TABLE IF NOT EXISTS app.test_session_categories (
    test_session_id BIGINT NOT NULL,
    category_id     BIGINT NOT NULL,

    PRIMARY KEY (test_session_id, category_id),

    CONSTRAINT fk_test_session_categories_session
        FOREIGN KEY (test_session_id)
        REFERENCES app.test_sessions (id)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    CONSTRAINT fk_test_session_categories_category
        FOREIGN KEY (category_id)
        REFERENCES app.phrase_categories (id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS app.test_session_accents (
    test_session_id BIGINT NOT NULL,
    accent_id       BIGINT NOT NULL,

    PRIMARY KEY (test_session_id, accent_id),

    CONSTRAINT fk_test_session_accents_session
        FOREIGN KEY (test_session_id)
        REFERENCES app.test_sessions (id)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    CONSTRAINT fk_test_session_accents_accent
        FOREIGN KEY (accent_id)
        REFERENCES app.accents (id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS app.test_session_noise_profiles (
    test_session_id   BIGINT NOT NULL,
    noise_profile_id  BIGINT NOT NULL,

    PRIMARY KEY (test_session_id, noise_profile_id),

    CONSTRAINT fk_test_session_noise_profiles_session
        FOREIGN KEY (test_session_id)
        REFERENCES app.test_sessions (id)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    CONSTRAINT fk_test_session_noise_profiles_noise_profile
        FOREIGN KEY (noise_profile_id)
        REFERENCES app.noise_profiles (id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT
);

-- ------------------------------------------------------------
-- 13. Вопросы, сформированные в рамках тестовой сессии
-- ------------------------------------------------------------

CREATE TABLE IF NOT EXISTS app.test_questions (
    id                        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    test_session_id           BIGINT NOT NULL,
    question_number           INTEGER NOT NULL,
    phrase_id                 BIGINT NOT NULL,
    accent_id                 BIGINT NOT NULL,
    noise_profile_id          BIGINT NOT NULL,
    audio_generation_id       BIGINT,
    correct_answer_text       TEXT NOT NULL,
    user_answer_text          TEXT,
    selected_answer_option_id BIGINT,
    is_correct                BOOLEAN,
    created_at                TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT fk_test_questions_session
        FOREIGN KEY (test_session_id)
        REFERENCES app.test_sessions (id)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    CONSTRAINT fk_test_questions_phrase
        FOREIGN KEY (phrase_id)
        REFERENCES app.aviation_phrases (id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT fk_test_questions_accent
        FOREIGN KEY (accent_id)
        REFERENCES app.accents (id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT fk_test_questions_noise_profile
        FOREIGN KEY (noise_profile_id)
        REFERENCES app.noise_profiles (id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT fk_test_questions_audio_generation
        FOREIGN KEY (audio_generation_id)
        REFERENCES app.audio_generations (id)
        ON UPDATE CASCADE
        ON DELETE SET NULL,

    CONSTRAINT fk_test_questions_selected_answer_option
        FOREIGN KEY (selected_answer_option_id)
        REFERENCES app.answer_options (id)
        ON UPDATE CASCADE
        ON DELETE SET NULL,

    CONSTRAINT chk_test_questions_question_number_positive
        CHECK (question_number > 0),
    CONSTRAINT chk_test_questions_correct_answer_not_blank
        CHECK (btrim(correct_answer_text) <> ''),

    CONSTRAINT uq_test_questions_session_number
        UNIQUE (test_session_id, question_number)
);

-- ------------------------------------------------------------
-- 14. Варианты ответов, показанные в конкретном вопросе
-- ------------------------------------------------------------

CREATE TABLE IF NOT EXISTS app.test_question_options (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    test_question_id BIGINT NOT NULL,
    answer_option_id BIGINT NOT NULL,
    option_order     INTEGER NOT NULL,

    CONSTRAINT fk_test_question_options_question
        FOREIGN KEY (test_question_id)
        REFERENCES app.test_questions (id)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    CONSTRAINT fk_test_question_options_answer_option
        FOREIGN KEY (answer_option_id)
        REFERENCES app.answer_options (id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT chk_test_question_options_order_range
        CHECK (option_order BETWEEN 1 AND 4),

    CONSTRAINT uq_test_question_options_question_option
        UNIQUE (test_question_id, answer_option_id),

    CONSTRAINT uq_test_question_options_question_order
        UNIQUE (test_question_id, option_order)
);

-- ------------------------------------------------------------
-- 15. Индексы для внешних ключей и типовых запросов
-- ------------------------------------------------------------

CREATE INDEX IF NOT EXISTS idx_aviation_phrases_category_id
    ON app.aviation_phrases (category_id);

CREATE INDEX IF NOT EXISTS idx_aviation_phrases_is_active
    ON app.aviation_phrases (is_active);

CREATE INDEX IF NOT EXISTS idx_answer_options_phrase_id
    ON app.answer_options (phrase_id);

CREATE INDEX IF NOT EXISTS idx_answer_options_active_by_phrase
    ON app.answer_options (phrase_id, is_active);

CREATE INDEX IF NOT EXISTS idx_audio_generations_phrase_id
    ON app.audio_generations (phrase_id);

CREATE INDEX IF NOT EXISTS idx_audio_generations_params
    ON app.audio_generations (phrase_id, accent_id, noise_profile_id);

CREATE INDEX IF NOT EXISTS idx_audio_generations_created_at
    ON app.audio_generations (created_at);

CREATE INDEX IF NOT EXISTS idx_test_sessions_started_at
    ON app.test_sessions (started_at);

CREATE INDEX IF NOT EXISTS idx_test_questions_session_id
    ON app.test_questions (test_session_id);

CREATE INDEX IF NOT EXISTS idx_test_questions_audio_generation_id
    ON app.test_questions (audio_generation_id);

CREATE INDEX IF NOT EXISTS idx_test_question_options_question_id
    ON app.test_question_options (test_question_id);

-- ------------------------------------------------------------
-- 16. Комментарии к таблицам
-- ------------------------------------------------------------

COMMENT ON TABLE app.phrase_categories IS 'Справочник категорий авиационных фраз.';
COMMENT ON TABLE app.aviation_phrases IS 'Учебные авиационные фразы для тренировки и тестирования.';
COMMENT ON TABLE app.accents IS 'Справочник доступных акцентов для синтеза речи.';
COMMENT ON TABLE app.noise_profiles IS 'Справочник акустических условий и шумовых профилей.';
COMMENT ON TABLE app.answer_options IS 'Варианты ответов для тестирования с выбором ответа.';
COMMENT ON TABLE app.audio_generations IS 'История формирования аудиофайлов WAV.';
COMMENT ON TABLE app.test_sessions IS 'Сведения о прохождении тестирования.';
COMMENT ON TABLE app.test_session_categories IS 'Категории, выбранные пользователем для тестовой сессии.';
COMMENT ON TABLE app.test_session_accents IS 'Акценты, выбранные пользователем для тестовой сессии.';
COMMENT ON TABLE app.test_session_noise_profiles IS 'Акустические условия, выбранные пользователем для тестовой сессии.';
COMMENT ON TABLE app.test_questions IS 'Вопросы, сформированные в рамках тестовой сессии.';
COMMENT ON TABLE app.test_question_options IS 'Варианты ответов, показанные пользователю в конкретном вопросе.';
