-- ============================================================
-- Миграция БД: пользователи, авторизация и отчёты преподавателя
-- Для уже созданной БД vkr_atc_training.
-- ============================================================

BEGIN;

SET search_path TO app, public;

-- ------------------------------------------------------------
-- 1. Учебные группы, ученики и преподаватели
-- ------------------------------------------------------------

CREATE TABLE IF NOT EXISTS app.student_groups (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_name  VARCHAR(64) NOT NULL UNIQUE,
    description TEXT,
    is_active   BOOLEAN NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT chk_student_groups_name_not_blank
        CHECK (btrim(group_name) <> '')
);

CREATE TABLE IF NOT EXISTS app.students (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id      BIGINT,
    login         VARCHAR(128) NOT NULL UNIQUE,
    password_hash TEXT NOT NULL,
    full_name     VARCHAR(255) NOT NULL,
    email         VARCHAR(255),
    is_active     BOOLEAN NOT NULL DEFAULT TRUE,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT fk_students_group
        FOREIGN KEY (group_id)
        REFERENCES app.student_groups (id)
        ON UPDATE CASCADE
        ON DELETE SET NULL,

    CONSTRAINT chk_students_login_not_blank
        CHECK (btrim(login) <> ''),
    CONSTRAINT chk_students_password_hash_not_blank
        CHECK (btrim(password_hash) <> ''),
    CONSTRAINT chk_students_full_name_not_blank
        CHECK (btrim(full_name) <> '')
);

CREATE TABLE IF NOT EXISTS app.teachers (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    login         VARCHAR(128) NOT NULL UNIQUE,
    password_hash TEXT NOT NULL,
    full_name     VARCHAR(255) NOT NULL,
    email         VARCHAR(255),
    department    VARCHAR(255),
    is_active     BOOLEAN NOT NULL DEFAULT TRUE,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT chk_teachers_login_not_blank
        CHECK (btrim(login) <> ''),
    CONSTRAINT chk_teachers_password_hash_not_blank
        CHECK (btrim(password_hash) <> ''),
    CONSTRAINT chk_teachers_full_name_not_blank
        CHECK (btrim(full_name) <> '')
);

-- ------------------------------------------------------------
-- 2. Переименование runtime-таблиц: session -> attempt
-- ------------------------------------------------------------
-- Тестовая сессия по смыслу является попыткой прохождения теста.
-- Поэтому таблицы переименовываются в test_attempts и связанные таблицы.

DO $$
BEGIN
    IF to_regclass('app.test_sessions') IS NOT NULL AND to_regclass('app.test_attempts') IS NULL THEN
        ALTER TABLE app.test_sessions RENAME TO test_attempts;
    END IF;
END $$;

DO $$
BEGIN
    IF to_regclass('app.test_session_categories') IS NOT NULL AND to_regclass('app.test_attempt_categories') IS NULL THEN
        ALTER TABLE app.test_session_categories RENAME TO test_attempt_categories;
    END IF;
END $$;

DO $$
BEGIN
    IF to_regclass('app.test_session_accents') IS NOT NULL AND to_regclass('app.test_attempt_accents') IS NULL THEN
        ALTER TABLE app.test_session_accents RENAME TO test_attempt_accents;
    END IF;
END $$;

DO $$
BEGIN
    IF to_regclass('app.test_session_noise_profiles') IS NOT NULL AND to_regclass('app.test_attempt_noise_profiles') IS NULL THEN
        ALTER TABLE app.test_session_noise_profiles RENAME TO test_attempt_noise_profiles;
    END IF;
END $$;

DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = 'app' AND table_name = 'test_attempt_categories' AND column_name = 'test_session_id'
    ) THEN
        ALTER TABLE app.test_attempt_categories RENAME COLUMN test_session_id TO test_attempt_id;
    END IF;
END $$;

DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = 'app' AND table_name = 'test_attempt_accents' AND column_name = 'test_session_id'
    ) THEN
        ALTER TABLE app.test_attempt_accents RENAME COLUMN test_session_id TO test_attempt_id;
    END IF;
END $$;

DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = 'app' AND table_name = 'test_attempt_noise_profiles' AND column_name = 'test_session_id'
    ) THEN
        ALTER TABLE app.test_attempt_noise_profiles RENAME COLUMN test_session_id TO test_attempt_id;
    END IF;
END $$;

DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = 'app' AND table_name = 'test_questions' AND column_name = 'test_session_id'
    ) THEN
        ALTER TABLE app.test_questions RENAME COLUMN test_session_id TO test_attempt_id;
    END IF;
END $$;

-- ------------------------------------------------------------
-- 3. Связь попытки тестирования с учеником
-- ------------------------------------------------------------

ALTER TABLE app.test_attempts
    ADD COLUMN IF NOT EXISTS student_id BIGINT;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'fk_test_attempts_student'
          AND conrelid = 'app.test_attempts'::regclass
    ) THEN
        ALTER TABLE app.test_attempts
            ADD CONSTRAINT fk_test_attempts_student
            FOREIGN KEY (student_id)
            REFERENCES app.students (id)
            ON UPDATE CASCADE
            ON DELETE SET NULL;
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_students_group_id
    ON app.students (group_id);

CREATE INDEX IF NOT EXISTS idx_test_attempts_student_id
    ON app.test_attempts (student_id);

CREATE INDEX IF NOT EXISTS idx_test_attempts_finished_at
    ON app.test_attempts (finished_at);

-- ------------------------------------------------------------
-- 4. Демонстрационные пользователи для первого запуска
-- ------------------------------------------------------------
-- Логин/пароль ученика: student1 / student123
-- Логин/пароль преподавателя: teacher1 / teacher123
-- Пароли хранятся в виде PBKDF2-SHA256-хэша, а не открытым текстом.

INSERT INTO app.student_groups (group_name, description)
VALUES ('ИС-221', 'Демонстрационная учебная группа')
ON CONFLICT (group_name) DO UPDATE SET
    description = EXCLUDED.description,
    is_active = TRUE;

INSERT INTO app.students (group_id, login, password_hash, full_name, email, is_active)
SELECT
    g.id,
    'student1',
    'pbkdf2_sha256$260000$73747564656e74315f73616c745f3132$371a40ea9c72ef53de3fbb3b519c95beb8f3ddbf1c0861b46407fb8830cfb88c',
    'Иванов Иван Иванович',
    NULL,
    TRUE
FROM app.student_groups g
WHERE g.group_name = 'ИС-221'
ON CONFLICT (login) DO UPDATE SET
    group_id = EXCLUDED.group_id,
    password_hash = EXCLUDED.password_hash,
    full_name = EXCLUDED.full_name,
    email = EXCLUDED.email,
    is_active = TRUE;

INSERT INTO app.teachers (login, password_hash, full_name, email, department, is_active)
VALUES (
    'teacher1',
    'pbkdf2_sha256$260000$74656163686572315f73616c745f3132$6151f8a72e2907efd9088c0226882bc5b171a908a4610acce5534450d927a1f2',
    'Петров Пётр Петрович',
    NULL,
    'Кафедра ВМКСС',
    TRUE
)
ON CONFLICT (login) DO UPDATE SET
    password_hash = EXCLUDED.password_hash,
    full_name = EXCLUDED.full_name,
    email = EXCLUDED.email,
    department = EXCLUDED.department,
    is_active = TRUE;

COMMENT ON TABLE app.student_groups IS 'Справочник учебных групп учеников-диспетчеров.';
COMMENT ON TABLE app.students IS 'Ученики-диспетчеры, проходящие обучение и тестирование.';
COMMENT ON TABLE app.teachers IS 'Преподаватели, просматривающие результаты тестирования.';
COMMENT ON TABLE app.test_attempts IS 'Попытки прохождения тестирования учениками.';
COMMENT ON TABLE app.test_attempt_categories IS 'Категории, выбранные для попытки тестирования.';
COMMENT ON TABLE app.test_attempt_accents IS 'Акценты, выбранные для попытки тестирования.';
COMMENT ON TABLE app.test_attempt_noise_profiles IS 'Акустические условия, выбранные для попытки тестирования.';

COMMIT;
